ARG PHP_VERSION=8.3
FROM php:${PHP_VERSION}-fpm

ARG UID=1000
ARG GID=1000

RUN apt-get update && apt-get install -y \
    libpng-dev \
    libjpeg-dev \
    libfreetype6-dev \
    libzip-dev \
    libicu-dev \
    libonig-dev \
    libxml2-dev \
    libpq-dev \
    unzip \
    git \
    curl \
    zip \
    nano \
    default-mysql-client \
    postgresql-client \
    gnupg \
    ca-certificates \
    lsb-release \
    openssl \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install \
        mysqli \
        pdo \
        pdo_mysql \
        pdo_pgsql \
        pgsql \
        gd \
        intl \
        mbstring \
        zip \
        exif \
        bcmath \
        opcache \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
COPY php/php.ini /usr/local/etc/php/php.ini

RUN touch /var/log/php_errors.log \
    && chmod 666 /var/log/php_errors.log \
    && usermod -u ${UID} www-data \
    && groupmod -g ${GID} www-data \
    && chown -R www-data:www-data /var/www \
    && chown -R www-data:www-data /var/log/php_errors.log

WORKDIR /var/www/html

CMD ["php-fpm"]
