map $host $project_name {
    default "";
    localhost2 joomla6;
    ~^(?<project>[^.]+)\.localhost2$ $project;
    ~^(?<project>[^.]+)\.2\.localhost$ $project;
    ~^(?<project>[^.]+)\.localhost$ $project;
}

map $project_name $project_root {
    default /var/www/html/$project_name;
    hirleicarlos-github-io /var/www/html/meg-load/hirleicarlos-github-io;
    "" /var/www/html;
}

resolver 127.0.0.11 valid=30s ipv6=off;

server {
    listen 80;
    server_name localhost localhost2 *.localhost2 *.2.localhost *.localhost;

    root $project_root;
    index index.php index.html index.htm;

    client_max_body_size 10G;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        set $php_fpm_upstream php-fpm:9000;
        fastcgi_pass $php_fpm_upstream;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}

server {
    listen 443 ssl;
    server_name localhost localhost2 *.localhost2 *.2.localhost *.localhost;

    ssl_certificate /etc/nginx/ssl/localhost.crt;
    ssl_certificate_key /etc/nginx/ssl/localhost.key;

    root $project_root;
    index index.php index.html index.htm;

    client_max_body_size 10G;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        set $php_fpm_upstream php-fpm:9000;
        fastcgi_pass $php_fpm_upstream;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}
