UseCanonicalName Off
VirtualDocumentRoot /var/www/html/%-2.0

<VirtualHost *:443>
    ServerName localhost
    ServerAlias *.localhost

    SSLEngine on
    SSLCertificateFile /etc/apache2/ssl/localhost.crt
    SSLCertificateKeyFile /etc/apache2/ssl/localhost.key

    <Directory /var/www/html>
        Options Indexes FollowSymLinks
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>